version: '3.8'

services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4650:4650"
    environment:
      - NODE_ENV=production
      - PORT=4650
    restart: unless-stopped
